AWS_BUCKET_NAME: "pixelmap.dev"
AWS_ID: # Pass in via CLI!
AWS_SECRET: # Pass in via CLI!
CONTRACT_ADDRESS: "0x015a06a433353f8db634df4eddf0c109882a15ab"
CONTRACT_WRAPPER_ADDRESS: "0x050dc61dfb867e0fe3cf2948362b6c0f3faf790b"
URLS:
  - "api.pixelmap.dev"
WEB3_URL: # pass in via CLI

#AWS_BUCKET_NAME: "pixelmap.dev"
#AWS_ID: # Pass in via CLI!
#AWS_SECRET: # Pass in via CLI!
#CONTRACT_ADDRESS: "0x41FDA36c7eF22b2A547E141ec52Af5D65F44B1f9"
#CONTRACT_WRAPPER_ADDRESS: "0x576D004Add5c529F81a50fD187e03be72f390b96"
#DOMAIN: "pixelmap.dev"
#WEB3_URL: "wss://ropsten.infura.io/ws/v3/7bf4c0b0cd4947c0a26c2fcde3f1b4fe" # Ropsten
